# Ember Protocol Server Configuration

# Game Settings
MAP_WIDTH = 400
MAP_HEIGHT = 400
MAP_SEED = 42
TICK_INTERVAL = 2  # seconds

# Agent Settings
MAX_AGENTS = 50
AGENT_RESPONSE_TIMEOUT = 1.8  # seconds (must be < tick interval)
HEARTBEAT_TIMEOUT = 120  # seconds
AUTO_LOGOUT_TIMEOUT = 600  # seconds

# Combat Settings
UNARMED_DAMAGE = 2
CREATURE_DAMAGE = 5
CREATURE_AGGRO_RANGE = 4

# Energy Settings
BUILTIN_SOLAR_CHARGE = 1
REST_CHARGE = 3
POWER_NODE_WIRELESS_CHARGE = 2
SOLAR_ARRAY_CHARGE = 5
BATTERY_RESTORE = 30

# Map Settings
ENCLOSURE_MAX_TILES = 64
WOOD_RENEWAL_RANGE = 3
WOOD_RENEWAL_TICKS = 600

# Weather Settings
STORM_MIN_INTERVAL = 300
STORM_MAX_INTERVAL = 600
STORM_DURATION = 20

# Day/Night
DAY_CYCLE_TICKS = 900
DAY_TICKS = 420
DUSK_TICKS = 30
NIGHT_TICKS = 420
DAWN_TICKS = 30
